name: Dockerize

on:
  push:
    tags:
      - 'v*.*.*'

  dependencies:
    - test

env:
  CARGO_TERM_COLOR: always

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          - platforms: arm64,riscv64,arm
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Dockerize
        run: buildx build --platform linux/arm64,linux/amd64 --tag chaincase/nolooking:${{ env.RELEASE_VERSION }} --output type=registry .
